export const VENDOR_LOGOS = {
  "MedSupply Inc.": "https://medsupplyinc.com/images/medsupply-logo-min.png",
  "Hospital Direct": "https://www.hospitaldirect.co.uk/wp-content/uploads/2022/11/hlogo-300x225.png",
  "McKesson": "https://www.mckesson.com/assets/img/mckesson-logo.svg",
  "Medline": "https://www.medline.com/wp-content/uploads/2021/03/medline-logo.png",
  "Cardinal Health": "https://www.cardinalhealth.com/content/dam/corp/web/images/cardinal-health-logo.png",
  "Henry Schein": "https://www.henryschein.com/images/hs-logo.svg",
  "Owens & Minor": "https://www.owens-minor.com/wp-content/themes/owens-minor/assets/images/om-logo.svg",
  "Becton Dickinson": "https://www.bd.com/assets/images/bd-logo.svg",
  "PPE Direct": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTpI8MV2cGuu0DNQGnsswtmsjP7Cxi19uN-Q&s",
  "3M Healthcare": "https://www.3m.com/3M/en_US/health-care-us/images/3m-healthcare-logo.png",
  "Abbott Nutrition": "https://www.abbottnutrition.com/images/abbott-nutrition-logo.png",
  "Bard Medical - A Div of BD": "https://www.bd.com/assets/images/bard-medical-logo.png",
  "Baxter Healthcare": "https://www.baxter.com/sites/g/files/ebysai746/files/baxter-logo.png",
  "BD Medical - Div of BD Worldwide": "https://www.bd.com/assets/images/bd-medical-logo.png",
  "Cardinal Health Inc": "https://www.cardinalhealth.com/content/dam/corp/web/images/cardinal-health-logo.png",
  "Corning Inc": "https://www.corning.com/content/dam/corning/logo.png",
  "Dasco Label": "https://www.dascolabel.com/images/dasco-label-logo.png",
  "International Paper": "https://www.internationalpaper.com/content/dam/internationalpaper/logo.png",
  "Maquet Inc - Getinge Group": "https://www.getinge.com/dam/corporate/logo.png",
  "Medline Industries Inc": "https://www.medline.com/wp-content/uploads/2021/03/medline-logo.png",
  "Philips Healthcare": "https://www.usa.philips.com/healthcare/images/philips-healthcare-logo.png",
  "Sage Products LLC": "https://sageproducts.com/wp-content/themes/sage-products/images/sage-logo.png",
  "Westmed - Acq by Sunmed": "https://www.westmedinc.com/images/westmed-logo.png",
  "Medtronic MITG": "https://www.medtronic.com/content/dam/medtronic-com/global/logos/medtronic-logo.png",
  "Discount Medical": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgAToj7h6o_3F_dj4-WyRaaQG8GDIMDvsjoA&s",
  "default": "https://res.cloudinary.com/dk2/image/upload/v1/medical-supplies/vendors/default.png"
} as const; 